Fix/crashlytics groups Napier error messages
Q42/Template.Android pull request #76
Opened 2024-09-10 09:38 UTC by ninovanhooff

## Why is this important?

## Notes

2025-02-07 09:15 UTC, sebaslogen requested changes
There is a possible crash in the crashlog but besides that, the idea is solid, because this is only in the case the error is logged without an actual exception with stacktrace, so creating your own synthetic stacktrace seems like a logical step to trace the error back to where it was created 👍

2025-02-07 09:15 UTC, sebaslogen commented on app/src/main/kotlin/nl/q42/template/logging/CrashlyticsLogger.kt
> +        val lastToRemove = stackTrace[numToRemove - 1]
We can't never be 💯 % sure there are 8 items in the stacktrace array, so this could either throw an IndexOutOfBounds exception or return null, in the later case, then the `if` below should crash accessing the className, but since this code compiles I assume the array accessor is not nullable and simply throws an exception.
Would you  mind checking if this is the case and if so try to prevent it?

2025-02-07 09:15 UTC, sebaslogen commented on app/src/main/kotlin/nl/q42/template/logging/CrashlyticsLogger.kt
> +        if (lastToRemove.className != "io.github.aakira.napier.Napier" || lastToRemove.methodName != "e\$default"){
```suggestion
        if (lastToRemove.className != io.github.aakira.napier.Napier::class.java.name || lastToRemove.methodName != "e\$default"){
```

Could we substitute `io.github.aakira.napier.Napier` as a string for the actual reference to the library? That should make the solution less fragile

2025-02-27 13:27 UTC, ninovanhooff commented
Example of logged event: https://console.firebase.google.com/u/0/project/template-android-799ab/crashlytics/app/android:nl.q42.template.dev/issues/d4f44a7e0ef82893fca70be52bd6ec1f?time=last-seven-days&sessionEventKey=67C06615009D00012CA0ECCB462DD4C0_2054533272261167042

2025-02-27 13:30 UTC, ninovanhooff commented on app/src/main/kotlin/nl/q42/template/logging/CrashlyticsLogger.kt
> +        val lastToRemove = stackTrace[numToRemove - 1]
yep, done

2025-02-27 13:35 UTC, ninovanhooff commented
Fixes #57

2025-02-28 07:14 UTC, sebaslogen approved these changes

2025-02-28 07:15 UTC, merged